version: "3"

networks:
  default:

services:
  service:
    image: ${DOCKER_IMAGE}
    user: clamav:clamav
    depends_on:
      - freshclam
    environment:
      - CLAMAV_UPDATE=true
      - CLAMAV_UPDATE_OPTS=--update-db=main
      - ENTRYPOINT_DEBUG=true
    volumes:
      - clamav_data:/var/lib/clamav

  freshclam:
    image: ${DOCKER_IMAGE}
    command: --daemon
    environment:
      - CLAMAV_HOST=service
      - DEFAULT_COMMAND=/usr/bin/freshclam
      - ENTRYPOINT_DEBUG=true
      - WAIT_FOR_TCP=service:3310
      - WAIT_FOR_TIMEOUT=60
    volumes:
      - clamav_data:/var/lib/clamav

  test:
    image: ${TEST_IMAGE}
    command: ${TEST_CMD}
    depends_on:
      - service
    env_file:
      - ${TEST_ENV_FILE}
    environment:
      - ENTRYPOINT_DEBUG=true
      # Wait until the tested service is started
      - WAIT_FOR_TCP=service:3310
      - WAIT_FOR_TIMEOUT=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Use project dir as host volume for debugging tests if Docker host is local
      - ${TEST_PROJECT_DIR:-test_project_dir}:${PROJECT_DIR}
    working_dir: ${TEST_DIR}

  wait:
    image: ${TEST_IMAGE}
    depends_on:
      - service
    environment:
      - ENTRYPOINT_DEBUG=true
      # Wait until the tested service is started
      - WAIT_FOR_TCP=service:3310
      - WAIT_FOR_TIMEOUT=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  clamav_data:
  test_project_dir:
